# Generated by Django 6.0 on 2026-01-02 14:54

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_np', models.CharField(max_length=100)),
                ('icon_name', models.CharField(blank=True, help_text="Icon identifier (e.g., 'road', 'water', 'electricity')", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Complaint Categories',
                'ordering': ['order', 'name_np'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('citizen_phone', models.CharField(blank=True, help_text='For anonymous submissions', max_length=15)),
                ('title', models.CharField(blank=True, help_text='Short title', max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/%Y/%m/%d')),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='voice/%Y/%m/%d')),
                ('location_text', models.CharField(blank=True, help_text='Ward, area description', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'प्रक्रियामा'), ('IN_PROGRESS', 'जाँच भइरहेको'), ('RESOLVED', 'समाधान भयो'), ('REJECTED', 'अस्वीकृत')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for officials')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, help_text='When offline data was synced', null=True)),
                ('client_created_at', models.DateTimeField(blank=True, help_text='Timestamp from offline device', null=True)),
                ('is_offline_submission', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='complains.complainscategory')),
                ('citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='complains_c_created_d1b52c_idx'), models.Index(fields=['status'], name='complains_c_status_67ae7e_idx'), models.Index(fields=['complaint_id'], name='complains_c_complai_cb5dd7_idx')],
            },
        ),
    ]
